Add comma detection to bg conversion. Fixes #122
reddit-diabetes/diabot-discord pull request #134
Opened 2021-10-03 21:25 UTC by Adidushi

Small fix that adds support for commas instead of dots when typing bg values for conversion.

2021-10-04 05:40 UTC, p5nbTgip0r commented
Could you rebase the PR branch on the latest `main` branch?

2021-10-04 16:06 UTC, Adidushi commented
A little messy because I suck at git, but it should be alright now.

2021-10-05 01:29 UTC, p5nbTgip0r requested changes
Just a small formatting change

2021-10-05 01:29 UTC, p5nbTgip0r commented on src/main/java/com/dongtronic/diabot/platforms/discord/listeners/ConversionListener.kt
> +            if(numberString.contains(',')) {
```suggestion
            if (numberString.contains(',')) {
```

2021-10-05 07:11 UTC, Adidushi commented on src/main/java/com/dongtronic/diabot/platforms/discord/listeners/ConversionListener.kt
> +            if(numberString.contains(',')) {
Added in commit 8c2248f8

2021-10-05 07:13 UTC, cascer1 approved these changes

2021-10-05 07:15 UTC, p5nbTgip0r approved these changes

2021-10-05 07:16 UTC, merged