Add recursive searching for multiple conversions
reddit-diabetes/diabot-discord pull request #136
Opened 2021-10-07 10:53 UTC by Adidushi

Fixes #11

2021-10-07 10:53 UTC, Adidushi commented
Currently gross as hell, probably looking at a full rewrite of the file

2021-10-25 06:47 UTC, cascer1 commented
I see a lot of duplicate code right now. Can you move all the logic to a single method and make that recursive instead?

2021-10-25 06:47 UTC, cascer1 requested changes
https://github.com/reddit-diabetes/diabot/pull/136#issuecomment-950581544

2021-10-27 12:39 UTC, cascer1 approved these changes

2021-10-27 12:39 UTC, merged