Add support for slash commands
reddit-diabetes/diabot-discord pull request #142
Opened 2021-10-28 17:36 UTC by cascer1

Begin adding support for slash commands.

This PR includes slash commands for some Nightscout settings, A1c estimations, and blood glucose conversion.

2021-10-29 01:14 UTC, p5nbTgip0r requested changes
Looks pretty good so far. Just a few questions and suggestions.

2021-10-29 01:14 UTC, p5nbTgip0r commented on bot/src/main/java/com/dongtronic/diabot/platforms/discord/commands/nightscout/NightscoutSlashCommand.kt
> +            event.reply("Your nightscout data was made $visibility in this server").setEphemeral(true).queue()
I think all of the `nightscout`s in response messages should be capitalized so the capitalization is consistent with other references

2021-10-29 01:14 UTC, p5nbTgip0r commented on bot/src/main/java/com/dongtronic/diabot/Main.kt
> +            val jda = shardManager.shards.first()
Shouldn't this loop through all the shards instead of only grabbing the first one?

2021-10-29 01:14 UTC, p5nbTgip0r commented on bot/src/main/java/com/dongtronic/diabot/platforms/discord/listeners/SlashCommandListener.kt
> +        if (commandClass != null ) {
```suggestion
        if (commandClass != null) {
```

2021-10-29 01:14 UTC, p5nbTgip0r commented on bot/src/main/java/com/dongtronic/diabot/platforms/discord/commands/diabetes/ConversionSlashCommand.kt
> +                .addOption(OptionType.STRING, commandArgUnit, "Blood glucose unit (mmol/L, mg/dL)")
```suggestion
                .addOptions(
                        OptionData(OptionType.STRING, commandArgUnit, "Blood glucose unit (mmol/L, mg/dL)")
                                .addChoice("mmol/L", "mmol/L")
                                .addChoice("mg/dL", "mg/dL")
                )
```

This would probably make it easier for users by making them choose a unit rather than type it

2021-10-29 01:14 UTC, p5nbTgip0r commented on bot/src/main/java/com/dongtronic/diabot/platforms/discord/commands/diabetes/EstimationSlashCommand.kt
> +                        .addOption(OptionType.STRING, commandArgUnit, "Glucose unit (mmol/L, mg/dL)"),
```suggestion
                        .addOptions(
                                OptionData(OptionType.STRING, commandArgUnit, "Glucose unit (mmol/L, mg/dL)")
                                        .addChoice("mmol/L", "mmol/L")
                                        .addChoice("mg/dL", "mg/dL")
                        ),
```

2021-10-29 01:14 UTC, p5nbTgip0r commented on bot/src/main/java/com/dongtronic/diabot/platforms/discord/commands/nightscout/NightscoutSlashCommand.kt
> +                        SubcommandData(commandModePublic, "Set nightscout to public in the current server")
Rather than having separate commands for setting the privacy to public or private (with the public command having a boolean to set it to private), would it be better to have one command like `/nightscout set privacy` with two choices for `public` and `private`?

2021-10-29 01:14 UTC, p5nbTgip0r commented on bot/src/main/java/com/dongtronic/diabot/platforms/discord/commands/nightscout/NightscoutSlashCommand.kt
> +                        SubcommandData(commandModeToken, "Get nightscout token")
With the addition of 'get' commands, should there also be a command to get a list of guilds where the user's Nightscout data is public? This could be added in a future pull request, it's just an idea

2021-10-29 07:59 UTC, cascer1 commented on bot/src/main/java/com/dongtronic/diabot/Main.kt
> +            val jda = shardManager.shards.first()
no because global commands are registered for the entire bot user, not a shard. The reason I use a guild command in debug mode is because those can be updated more frequently in the discord API.

2021-10-29 08:12 UTC, cascer1 commented on bot/src/main/java/com/dongtronic/diabot/platforms/discord/commands/nightscout/NightscoutSlashCommand.kt
> +                        SubcommandData(commandModeToken, "Get nightscout token")
Yes I like that idea. Perhaps also a command to immediately set it to private everywhere.

2021-10-29 09:20 UTC, p5nbTgip0r commented on bot/src/main/java/com/dongtronic/diabot/platforms/discord/commands/nightscout/NightscoutSlashCommand.kt
> +                        SubcommandData(commandModeToken, "Get nightscout token")
That could be rolled under the delete command, like `/nightscout delete publicguilds` or similar to reset your privacy settings everywhere, since that's essentially what would be taking place

2021-10-31 07:20 UTC, p5nbTgip0r approved these changes
LGTM

2021-10-31 08:18 UTC, merged